config/routes.rb
Animal::Application.routes.draw do
  resources :cutes

  

end

app/models/cute.rb
class Cute < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cutes_controller.rb
class CutesController < ApplicationController
  before_action :set_cute, only: [:show, :edit, :update, :destroy]

  # GET /cutes
  # GET /cutes.json
  def index
    @cutes = Cute.all
  end

  # GET /cutes/1
  # GET /cutes/1.json
  def show
  end

  # GET /cutes/new
  def new
    @cute = Cute.new
  end

  # GET /cutes/1/edit
  def edit
  end

  # POST /cutes
  # POST /cutes.json
  def create
    @cute = Cute.new(cute_params)

    respond_to do |format|
      if @cute.save
        format.html { redirect_to @cute, notice: 'Cute was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cute }
      else
        format.html { render action: 'new' }
        format.json { render json: @cute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cutes/1
  # PATCH/PUT /cutes/1.json
  def update
    respond_to do |format|
      if @cute.update(cute_params)
        format.html { redirect_to @cute, notice: 'Cute was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cutes/1
  # DELETE /cutes/1.json
  def destroy
    @cute.destroy
    respond_to do |format|
      format.html { redirect_to cutes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cute
      @cute = Cute.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cute_params
      params.require(:cute).permit(:Animal, :image_url, :description, :level_of_cuteness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cutes_helper.rb
module CutesHelper
end

app/views/cutes/_form.html.erb
<%= form_for(@cute) do |f| %>
  <% if @cute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cute.errors.count, "error") %> prohibited this cute from being saved:</h2>

      <ul>
      <% @cute.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Animal %><br>
    <%= f.text_field :Animal %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :level_of_cuteness %><br>
    <%= f.number_field :level_of_cuteness %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cutes/edit.html.erb
<h1>Editing cute</h1>

<%= render 'form' %>

<%= link_to 'Show', @cute %> |
<%= link_to 'Back', cutes_path %>

app/views/cutes/index.html.erb
<div class="container">
  <div align="center">
<script src="http://code.jquery.com/jquery.min.js"></script>
<link href="http://getbootstrap.com/dist/css/bootstrap.css" rel="stylesheet" type="text/css" />
<script src="http://getbootstrap.com/dist/js/bootstrap.js"></script>
  <meta charset="utf-8">
<text-align:center>
<div class="jumbotron">
  <% @cutes.each do |cute| %>
  <h1>Baby Animals</h1>
  <p>IZZ SO FLUFFFY</p>
  <p><a href="http://kieran-91949.use1-2.nitrousbox.com/cutes/new" class="btn btn-primary btn-lg" role="button">create new animal</a></p>
 
  </div>

<div class="panel panel-default">
  <div class="panel-heading"><td><h2><%= cute.Animal %></h2></td></div>
  <div class="panel-body">
    
  





  <tbody>
   
      <tr>
        
        <td><img src="<%= cute.image_url %>"></td>
        
      <p>  
        <td><%= link_to 'Show |', cute %></td>
        <td><%= link_to 'Edit |', edit_cute_path(cute) %></td>
        <td><%= link_to 'Destroy', cute, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    </p>
    <% end %>
  </tbody>

<br>
    </div>
    </div>


<%= link_to 'New Animal', new_cute_path %>
  </div>

app/views/cutes/new.html.erb
<h1>New Animal</h1>

<%= render 'form' %>

<%= link_to 'Back', cutes_path %>

app/views/cutes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Animal:</strong>
  <%= @cute.Animal %>
</p>

<p>
  <strong><img src="<%= @cute.image_url%>"></strong>

</p>

<p>
  <h1><strong>Description:</strong></h1>
  <h3><%= @cute.description %><h3>
</p>

<p>
  <h1> <strong>Level of cuteness:</strong></h1>
    <h3> <%= @cute.level_of_cuteness %></h3>
</p>

<%= link_to 'Edit', edit_cute_path(@cute) %> |
<%= link_to 'Back', cutes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Animal</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>